'''

Compares the output of tjbd run in simulation mode using VCFs generated by
ped-sim with the ground-truth IBD segments from ped-sim.

Sam Vohr (svohr@soe.ucsc.edu)
Wed Aug 21 18:31:11 PDT 2019

'''
from __future__ import print_function, division

import sys
import argparse

import pandas


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('chrom', help='Chromosome number.')
    parser.add_argument('pedsim_segs_fn', help='Truth segments from ped-sim.')
    parser.add_argument('tjbd_segs_fn', help='Detected segments from tjbd.')
    parser.add_argument('tjbd_pos_fn', help='Positional output from tjbd.')

    args = parser.parse_args()

    pedsim_segs_df = pandas.read_csv(args.pedsim_segs_fn,
                                     sep='\t',
                                     names=['iid1', 'iid2',
                                            'chrom', 'start', 'end',
                                            'ibd', 'start_cm', 'end_cm',
                                            'size_cm'],
                                     dtype={'chrom': str})
    pedsim_segs_df = pedsim_segs_df[pedsim_segs_df['chrom'] == args.chrom]

    tjbd_segs_df = pandas.read_csv(args.tjbd_segs_fn, sep='\t')
    tjbd_pos_df = pandas.read_csv(args.tjbd_pos_fn, sep='\t')

    tjbd_pos_df['ibd_pedsim'] = False

    segment_tp = 0
    segment_fn = 0
    segment_fp = 0

    for _, seg in pedsim_segs_df.iterrows():
        seg_mask = ((tjbd_pos_df['pos'] >= seg['start'])
                    & (tjbd_pos_df['pos'] <= seg['end']))
        tjbd_pos_df.loc[seg_mask, 'ibd_pedsim'] = True

        segment_tp += tjbd_pos_df.loc[seg_mask, 'ibd_call'].any()
        segment_fn += not tjbd_pos_df.loc[seg_mask, 'ibd_call'].any()

    for _, seg in tjbd_segs_df.iterrows():
        seg_mask = ((tjbd_pos_df['pos'] >= seg['start'])
                    & (tjbd_pos_df['pos'] <= seg['end']))
        segment_fp += not tjbd_pos_df.loc[seg_mask, 'ibd_pedsim'].any()

    summary = pandas.Series()
    summary['n_segs_true'] = len(pedsim_segs_df)
    summary['n_segs_detected'] = len(tjbd_segs_df)
    summary['total_ibd_cm_true'] = pedsim_segs_df['size_cm'].sum()
    summary['total_ibd_cm_detected'] = tjbd_segs_df['genetic_length'].sum()

    summary['seg_tp'] = segment_tp
    summary['seg_fp'] = segment_fp
    summary['seg_fn'] = segment_fn

    summary['pos_tp'] = (tjbd_pos_df['ibd_pedsim']
                         & tjbd_pos_df['ibd_call']).sum()
    summary['pos_tn'] = (~tjbd_pos_df['ibd_pedsim']
                         & ~tjbd_pos_df['ibd_call']).sum()
    summary['pos_fp'] = (~tjbd_pos_df['ibd_pedsim']
                         & tjbd_pos_df['ibd_call']).sum()
    summary['pos_fn'] = (tjbd_pos_df['ibd_pedsim']
                         & ~tjbd_pos_df['ibd_call']).sum()

    print(summary)
    return 0


if __name__ == '__main__':
    sys.exit(main())
