'''

Compares the output of tjbd run in simulation mode using VCFs generated by
ped-sim with the ground-truth IBD segments from ped-sim.

Sam Vohr (svohr@soe.ucsc.edu)
Wed Aug 21 18:31:11 PDT 2019

'''
from __future__ import print_function, division

import sys
import argparse

import numpy
import pandas


def find_best_actual_seg_match(seg, pedsim_seg_df):

    full_range = (
        numpy.maximum(seg['end_cm'], pedsim_seg_df['end_cm'])
        - numpy.minimum(seg['start_cm'], pedsim_seg_df['start_cm']))
    overlap_range = (
        numpy.minimum(seg['end_cm'], pedsim_seg_df['end_cm'])
        - numpy.maximum(seg['start_cm'], pedsim_seg_df['start_cm']))

    total_unmatched = full_range - overlap_range

    if (overlap_range <= 0.0).all():
        return None

    return pedsim_seg_df.loc[total_unmatched[overlap_range > 0.0].idxmin()]


def overlaps_true_segment(seg, best_match_seg):
    overlap_total = (
        numpy.minimum(seg['end_cm'], best_match_seg['end_cm'])
        - numpy.maximum(seg['start_cm'], best_match_seg['start_cm']))
    return overlap_total > (seg['genetic_length'] / 2.0)


def compare_chromosome(chrom, pedsim_seg_df, tjbd_seg_df, tjbd_pos_df, min_size=0.0):
    tjbd_pos_df['ibd_pedsim'] = False

    segment_tp = 0
    segment_fn = 0
    segment_fp = 0

    true_segments = []
    detected_segments = []

    for _, seg in pedsim_seg_df.iterrows():
        seg_mask = ((tjbd_pos_df['pos'] >= seg['start'])
                    & (tjbd_pos_df['pos'] <= seg['end']))
        tjbd_pos_df.loc[seg_mask, 'ibd_pedsim'] = True

        detected = tjbd_pos_df.loc[seg_mask, 'ibd_call'].any()
        segment_fn += not detected

        true_segments.append({
            'chrom': chrom,
            'start': seg['start'],
            'end': seg['end'],
            'size_cm': seg['size_cm'],
            'size_bp': seg['end'] - seg['start'],
            'detected': int(detected),
            'missed': int(not detected),
            'max_posterior': tjbd_pos_df.loc[seg_mask, 'posterior'].max()})

    for _, seg in tjbd_seg_df.iterrows():
        seg_mask = ((tjbd_pos_df['pos'] >= seg['start'])
                    & (tjbd_pos_df['pos'] <= seg['end']))
        segment_tp += tjbd_pos_df.loc[seg_mask, 'ibd_pedsim'].any()
        segment_fp += not tjbd_pos_df.loc[seg_mask, 'ibd_pedsim'].any()

        best_match_seg = find_best_actual_seg_match(seg, pedsim_seg_df)

        overlaps_true = overlaps_true_segment(seg, best_match_seg)

        detected_segments.append({
            'chrom': chrom,
            'start': seg['start'],
            'end': seg['end'],
            'size_cm': seg['genetic_length'],
            'size_bp': seg['physical_length'],
            'true_positive': int(overlaps_true),
            'false_positive': int(not overlaps_true),
            'actual_size_cm': (
                0.0 if best_match_seg is None else best_match_seg['size_cm'])})

    summary = pandas.Series()
    summary['n_segs_true'] = len(pedsim_seg_df)
    summary['n_segs_true_detectable'] = (
        pedsim_seg_df['size_cm'] >= min_size).sum()
    summary['n_segs_detected'] = len(tjbd_seg_df)
    summary['total_ibd_cm_true'] = pedsim_seg_df['size_cm'].sum()
    summary['total_ibd_cm_true_detectable'] = pedsim_seg_df.loc[
        pedsim_seg_df['size_cm'] >= min_size, 'size_cm'].sum()
    summary['total_ibd_cm_detected'] = tjbd_seg_df['genetic_length'].sum()

    summary['seg_tp'] = segment_tp
    summary['seg_fp'] = segment_fp
    summary['seg_fn'] = segment_fn

    summary['pos_tp'] = (tjbd_pos_df['ibd_pedsim']
                         & tjbd_pos_df['ibd_call']).sum()
    summary['pos_tn'] = (~tjbd_pos_df['ibd_pedsim']
                         & ~tjbd_pos_df['ibd_call']).sum()
    summary['pos_fp'] = (~tjbd_pos_df['ibd_pedsim']
                         & tjbd_pos_df['ibd_call']).sum()
    summary['pos_fn'] = (tjbd_pos_df['ibd_pedsim']
                         & ~tjbd_pos_df['ibd_call']).sum()

    return summary, true_segments, detected_segments


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('pedsim_seg_fn', help='Truth segments from ped-sim.')
    parser.add_argument('tjbd_template',
                        help='Chromosome output template for tjbd, '
                             'e.g., "output_chr{}"')
    parser.add_argument('out_prefix', help='Prefix for output files')
    parser.add_argument('-m', '--min-size', type=float, default=0.0,
                        help='Minimum reported segment size.')
    args = parser.parse_args()

    all_pedsim_seg_df = pandas.read_csv(args.pedsim_seg_fn,
                                        sep='\t',
                                        names=['iid1', 'iid2',
                                               'chrom', 'start', 'end',
                                               'ibd', 'start_cm', 'end_cm',
                                               'size_cm'],
                                        dtype={'chrom': str, 'start': int,
                                               'end': int})

    chrom_summaries = []
    true_segments = []
    detected_segments = []
    for chrom in (str(c) for c in range(1, 23)):
        print(chrom, file=sys.stderr)
        pedsim_seg_df = all_pedsim_seg_df[all_pedsim_seg_df['chrom'] == chrom]

        tjbd_seg_fn = '{}.seg.tsv'.format(args.tjbd_template.format(chrom))
        tjbd_pos_fn = '{}.pos.tsv'.format(args.tjbd_template.format(chrom))

        tjbd_seg_df = pandas.read_csv(tjbd_seg_fn, sep='\t',
                                      dtype={'chrom': str, 'start': int,
                                             'end': int, 'n_snps': int,
                                             'physical_length': int})
        tjbd_pos_df = pandas.read_csv(tjbd_pos_fn, sep='\t',
                                      dtype={'chrom': str, 'pos': int})

        summary, true_segs, detected_segs = (
            compare_chromosome(chrom=chrom,
                               pedsim_seg_df=pedsim_seg_df,
                               tjbd_seg_df=tjbd_seg_df,
                               tjbd_pos_df=tjbd_pos_df,
                               min_size=args.min_size)
        )
        chrom_summaries.append(summary)
        true_segments += true_segs
        detected_segments += detected_segs

    summary = pandas.DataFrame(chrom_summaries).sum()

    true_segments_df = pandas.DataFrame(true_segments)
    detected_segments_df = pandas.DataFrame(detected_segments)

    summary.to_frame().T.to_csv('{}_summary.tsv'.format(args.out_prefix),
                                sep='\t', index=False, header=False)
    true_cols = ['chrom', 'start', 'end', 'size_cm', 'size_bp',
                 'detected', 'missed', 'max_posterior']
    true_segments_df[true_cols].to_csv(
        '{}_true_segs.tsv'.format(args.out_prefix), sep='\t', index=False)
    detected_cols = ['chrom', 'start', 'end', 'size_cm', 'size_bp',
                     'true_positive', 'false_positive', 'actual_size_cm']
    detected_segments_df[detected_cols].to_csv(
        '{}_detected_segs.tsv'.format(args.out_prefix), sep='\t', index=False)

    return 0


if __name__ == '__main__':
    sys.exit(main())
