#! /usr/bin/env python2
"""
This script takes composite haplotypes generated by the "composite_haps.py"
script, builds pairs of diploid individuals each sharing an IBD segment
with eachother, and runs a trial of the IBD detection HMM on all pairs of
individuals.
"""

from __future__ import print_function

import sys
import os
import argparse
import random
import itertools
import collections

import numpy

import recmap
import freqs
import ibd_hmm
import confusion


def read_composites(cmp_in):
    """
    Reads in a table produced by 'composite_haps.py' containing physical
    coordinates (chrm ID and position), genetic position, and observed alleles
    for composite haplotypes.

    Args:
        cmp_in: file containing composite haplotypes.
    Returns:
        pos: physical positions on the chromosome.
        gpos: genetic positions on the chromosome.
        haps: observed bases for each haplotype (column) and SNP (row).
    """
    pos = list()
    gpos = list()
    haps = list()

    for line in cmp_in:
        items = line.split('\t')
        pos.append(int(items[1]))
        gpos.append(float(items[2]))
        haps.append(items[3:])
    return numpy.array(pos), numpy.array(gpos), numpy.array(haps)


def generate_individuals(gpos, haps, n_indvs, segsize):
    """
    Takes the starting set of composite haplotypes and builds 'n_indvs'
    diploid individuals by choosing two haplotypes at random. Also
    generates IBD blocks for the given segment size for pairs of individuals
    i and i+1 for even i indexes.

    Args:
        gpos: genetic positions for each marker (used to generate IBD).
        haps: matrix of SNP markers (rows) and composite haplotypes (cols)
        n_indvs: An even number of individuals to generate from the starting
                 haplotypes.
        segsize: The size (in cMs) of IBD blocks to generate)
    Returns:
        indv_haps: matrix of individuals sharing IBD
        ibd_blocks: A dictionary storing the segments that are in IBD.
    """
    sample = random.sample(range(len(haps[0])), n_indvs * 2)
    indv_haps = haps[:, sample]

    # keep an empty vector for unrelated individuals
    no_ibd = pick_ibd_block(gpos, 0)
    no_ibd.flags.writeable = False
    ibd_blocks = collections.defaultdict(lambda: no_ibd)
    for i in xrange(0, n_indvs * 2, 4):
        donor = random.choice([0, 1])
        recpt = random.choice([2, 3])

        ibd_seg = pick_ibd_block(gpos, segsize)
        indv_haps[ibd_seg, i + recpt] = indv_haps[ibd_seg, i + donor]
        ibd_blocks[i / 2, (i / 2) + 1] = ibd_seg
        ibd_blocks[(i / 2) + 1, i / 2] = ibd_seg
    return indv_haps, ibd_blocks


def pick_ibd_block(gpos, segsize):
    """
    Pick a segment of size 'segsize' in centimorgans based on the given genetic
    positions.

    Args:
        gpos: a numpy vector of genetic positions (in cMs)
        segsize: A target segment size in (cMs)
    Returns:
        a mask (vector of bools) indicating whether a segment is in IBD.
    """
    ibd_start = random.uniform(gpos[0], gpos[-1] - segsize)
    return (gpos >= ibd_start) & (gpos < ibd_start + segsize)


def sample_historical(indv_haps, indv, coverage, err_rate):
    """
    Simulates low-coverage sequencing of a historic individual. Produces
    a vector of observed bases and a mask indicating which positions were
    observed.

    Args:
        indv_haps: numpy array of haplotypes.
        indv: ID for starting individual.
        coverage: amout of sequence coverage to simulate.
        err_rate: rate of base call errors (switch obs to a random base)
    Returns:
        obs_mask: a vector of booleans indicating which positions were
                  observed.
        lo_obs: a vector containing a single observation for each observed
                position.
    """
    def base_error(orig_base):
        '''
        Simulate a base call error by picking a base at random that is not
        the correct one.
        '''
        return random.choice([base for base in 'ACGT' if base != orig_base])

    obs_mask = numpy.random.poisson(coverage, indv_haps.shape[0]) == 1
    obs_chrm = numpy.random.choice([2 * indv, (2 * indv) + 1],
                                   indv_haps.shape[0])
    lo_obs = indv_haps[obs_mask, obs_chrm[obs_mask]]

    if err_rate > 0:
        error_pos = numpy.random.binomial(1, err_rate, lo_obs.shape[0]) == 1
        lo_obs[error_pos] = numpy.fromiter(
            (base_error(obs) for obs in lo_obs[error_pos]), dtype='c')
    return obs_mask, lo_obs


def encode_observations(indv_haps, indv, lo_obs):
    """
    Generates a vector containing the number of times the historical allele
    was found in the modern individual for each observed position (0, 1 or 2).

    Args:
        indv_haps: numpy array of haplotypes.
        indv: ID for diploid individual to compare.
        obs_mask: boolean vector indicating whether a position was observed
                  in the historical sample.
        lo_obs: vector of observed bases from historical sample
    Returns:
        A vector containing the number of times the historical base was found
        in the modern individual for each position (0, 1, or 2).
    """
    counts = numpy.zeros(len(lo_obs))
    for phase in [0, 1]:
        counts += indv_haps[:, (indv * 2) + phase] == lo_obs
    return counts


def get_frequencies(frqs, chrm, pos, obs):
    """
    Finds the allele frequencies for the bases observed at the given positions.

    Args:
        chrm: a chromosome ID
        pos: a list of chromosome positions (int)
        obs: a list of single base observations (string)
    Returns:
        a numpy vector of allele frequencies
    """
    return numpy.array([frqs.frequency(chrm, p, b)
                        for p, b in itertools.izip(pos, obs)])


def run_trial(rmap, frqs, indv_haps, ibd_blocks, pos, gpos, args):
    """
    Runs the IBD HMM on all permuations of individuals. A low-coverage sample
    is generated for each individual and compared against the full genotypes
    of all other individuals.
    """
    n_indv = indv_haps.shape[1] / 2
    results = confusion.TrialResults(args.trial_name,
                                     args.segsize,
                                     args.coverage,
                                     args.ngen,
                                     (args.min_run,
                                      args.max_run,
                                      args.min_len))
    for lo_samp in xrange(0, n_indv):
        # generate low-coverage.
        sub_mask, lo_obs = sample_historical(indv_haps, lo_samp,
                                             args.coverage, args.error_rate)
        # mask remaining haplotypes.
        sub_haps = indv_haps[sub_mask, ]
        sub_pos = pos[sub_mask]
        sub_gpos = gpos[sub_mask]

        lo_freq = get_frequencies(frqs, args.chrom, sub_pos, lo_obs)
        ibd_trs, noibd_trs = ibd_hmm.state_trans(rmap, args.ngen,
                                                 args.chrom, sub_pos)

        for hi_samp in xrange(0, n_indv):
            if lo_samp == hi_samp:
                continue
            hmm_observed = encode_observations(sub_haps, hi_samp, lo_obs)
            hmm_post_probs = ibd_hmm.forward_backward(args.ngen,
                                                      hmm_observed,
                                                      lo_freq,
                                                      ibd_trs,
                                                      noibd_trs)
            called_ibd = ibd_hmm.find_ibd_blocks(hmm_post_probs,
                                                 args.max_run,
                                                 args.min_run,
                                                 gpos,
                                                 args.min_len)
            results.update(sub_pos,
                           sub_gpos,
                           hmm_post_probs,
                           ibd_blocks[lo_samp, hi_samp][sub_mask],
                           called_ibd)
    return results


def write_trial_log(args):
    """
    Writes a log file containing all the parameters used in this trial.

    Args:
        args: The ArgumentParser namespace containing all options and values.
    """
    with open('{}/{}.log'.format(args.out_dir, args.trial_name),
              'w') as log_out:
        print(' '.join(sys.argv), file=log_out)
        for name, value in vars(args).items():
            print('{}: {}'.format(name, value), file=log_out)


def main():
    """
    Runs a trial of the IBD HMM used by tjbd with the given parameters.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("hap_fn", metavar="composite.haps", type=str,
                        help="File containing starting composite haplotypes.")
    parser.add_argument("frq_fn", metavar="frqs.count", type=str,
                        help="Allele counts by SNP site")
    parser.add_argument("rec_fn", metavar="recmap.tab", type=str,
                        help="Genetic distances in tab file.")
    parser.add_argument("-c", "--chrom", metavar="CHROM", type=str, default=1,
                        help="Chromosome ID")
    parser.add_argument("-g", "--gen", metavar="N", dest="ngen",
                        type=int, default=5,
                        help="Approximate number of generations between "
                             "low-coverage and high-coverage individuals.")
    parser.add_argument("-l", "--coverage", metavar="COVERAGE", default=0.01,
                        help="Sequencing coverage level to simulate for "
                             "low-coverage samples.")
    parser.add_argument("-e", "--error-rate", metavar="RATE", default=0.005,
                        help="Base call error rate for historical sample.")
    parser.add_argument("-s", "--seg-size", dest="segsize", type=float,
                        default=10.0, metavar="cM",
                        help="Size in cM of IBD segments to simulate")
    parser.add_argument("-n", "--n-indv", dest="n_indv", type=int,
                        default=None, metavar="N",
                        help="Number of individuals to simulate (must be even "
                             "and <= number of haplotypes / 2)")
    parser.add_argument("-m", dest="min_run", type=float, default=0.8,
                        help="Minimum post. prob to allow in a detected "
                             "IBD segment.")
    parser.add_argument("-M", dest="max_run", type=float,
                        metavar="M", default=0.98,
                        help="Call IBD runs using post. probs exceeding M.")
    parser.add_argument("-L", dest="min_len", type=float,
                        metavar="cM", default=0.0,
                        help="Minimum length of IBD segment to call.")
    parser.add_argument("-r", "--seed", type=int, default=None,
                        help="Set the seed for random numbers.")
    parser.add_argument("-t", "--trial-name", type=str, default='trial',
                        help="Set the name for this trial")
    parser.add_argument("-o", "--out-dir", type=str, default='trial',
                        help="Set the name of the output directory.")
    args = parser.parse_args()

    if args.seed is None:
        args.seed = random.randrange(2**32 - 1)
    numpy.random.seed(args.seed)
    random.seed(args.seed)

    write_trial_log(args)

    frqs = freqs.AlleleFreqs()
    with open(args.frq_fn, 'r') as frq_in:
        frqs.read_vcf_counts(frq_in)

    rmap = recmap.RecMap()
    with open(args.rec_fn, 'r') as rec_in:
        rmap.read_tab(rec_in)

    with open(args.hap_fn, 'r') as hap_in:
        pos, gpos, init_haps = read_composites(hap_in)

    # set number of test individuals if necessary
    if not args.n_indv or args.n_indv * 2 > init_haps.shape[1]:
        args.n_indv = init_haps.shape[1] / 2 / 2 * 2

    indv_haps, indv_ibd = generate_individuals(gpos,
                                               init_haps,
                                               args.n_indv,
                                               args.segsize)
    res = run_trial(rmap, frqs, indv_haps, indv_ibd, pos, gpos, args)

    if not os.path.exists(args.out_dir):
        os.makedirs(args.out_dir)
    res.dump('{}'.format(args.out_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
