"""
This script takes composite haplotypes generated by the "composite_haps.py"
script, builds pairs of diploid individuals each sharing an IBD segment
with eachother, and runs a trial of the IBD detection HMM on all pairs of
individuals.
"""

import sys
import argparse
import random

import numpy

import rec
import freqs


def read_composites(cmp_in):
    """
    Reads in a table produced by 'composite_haps.py' containing physical
    coordinates (chrm ID and position), genetic position, and observed alleles
    for composite haplotypes.

    Args:
        cmp_in: file containing composite haplotypes.
    Returns:
        pos: physical positions on the chromosome.
        gpos: genetic positions on the chromosome.
        haps: observed bases for each haplotype (column) and SNP (row).
    """
    hap_tab = numpy.loadtxt(cmp_in)
    pos = hap_tab[:, 1].astype(int)
    gpos = hap_tab[:, 2].astype(float)
    haps = hap_tab[:, 3:]
    return pos, gpos, haps


def generate_individuals(gpos, haps, n_indvs, segsize):
    """
    Takes the starting set of composite haplotypes and builds 'n_indvs'
    diploid individuals by choosing two haplotypes at random. Also
    generates IBD blocks for the given segment size for pairs of individuals
    i and i+1 for even i indexes.

    Args:
        gpos: genetic positions for each marker (used to generate IBD).
        haps: matrix of SNP markers (rows) and composite haplotypes (cols)
        n_indvs: An even number of individuals to generate from the starting
                 haplotypes.
        segsize: The size (in cMs) of IBD blocks to generate)
    Returns:
        indv_haps: matrix of individuals sharing IBD
        ibd_blocks: A dictionary storing the segments that are in IBD.
    """
    sample = random.sample(range(len(haps[0])), n_indvs * 2)
    indv_haps = haps[:, sample]
    ibd_blocks = dict()
    for i in xrange(n_indvs * 2, 4):
        donor = random.choice([0, 1])
        recpt = random.choice([2, 3])

        ibd_seg = pick_ibd_block(gpos, segsize)
        indv_haps[ibd_seg, i + recpt] = indv_haps[ibd_seg, i + donor]
        ibd_blocks[i % 2, (i % 2) + 1] = ibd_seg
        ibd_blocks[(i % 2) + 1, i % 2] = ibd_seg
    return indv_haps, ibd_blocks


def pick_ibd_block(gpos, segsize):
    """
    Pick a segment of size 'segsize' in centimorgans based on the given genetic
    positions.

    Args:
        gpos: a numpy vector of genetic positions (in cMs)
        segsize: A target segment size in (cMs)
    Returns:
        a mask (vector of bools) indicating whether a segment is in IBD.
    """
    ibd_start = random.uniform(gpos[0], gpos[-1] - segsize)
    return (gpos >= ibd_start) & (gpos < ibd_start + segsize)


def sample_historical(indv_haps, indv, coverage):
    """
    Simulates low-coverage sequencing of a historic individual. Produces
    a vector of observed bases and a mask indicating which positions where
    observed.

    Args:
        indv_haps: numpy array of haplotypes.
        indv: ID for starting individual.
        coverage: amout of sequence coverage to simulate.
    Returns:
        obs_mask: a vector of booleans indicating which positions were
                  observed.
        lo_obs: a vector containing a single observation for each observed
                position.
    """
    obs_mask = numpy.random.poisson(coverage, indv_haps.shape[0])
    return obs_mask, lo_obs


def encode_observations(indv_haps, indv, obs_mask, lo_obs):
    """
    Generates a vector containing the number of times the historical allele
    was found in the modern individual for each observed position (0, 1 or 2).

    Args:
        indv_haps: numpy array of haplotypes.
        indv: ID for diploid individual to compare.
        obs_mask: boolean vector indicating whether a position was observed
                  in the historical sample.
        lo_obs: vector of observed bases from historical sample
    Returns:
        A vector containing the number of times the historical base was found
        in the modern individual for each position (0, 1, or 2).
    """
    counts = numpy.zeros_like(obs_mask)
    for phase in [0, 1]:
        counts += (indv_haps[obs_mask, (indv * 2) + phase] == lo_obs)
    return counts


def run_trial(indv_haps, idb_blocks, coverage):
    """
    Runs the IBD HMM on all permuations of individuals. A low-coverage sample
    is generated for each individual and compared against the full genotypes
    of all other individuals.
    """
    for lo_samp in xrange(0, len(indv_haps), 2):
        # generate low-coverage.
        # mask remaining haplotypes.
        for hi_samp in xrange(0, len(indv_haps), 2):
            if lo_samp == hi_samp:
                continue
            # run comparison

    return


def main():
    return 0

if __name__ == "__main__":
    sys.exit(main())
