#! /usr/bin/env python
'''
tjbd detects IBD segments shared between a genome sequenced to high-coverage
with complete genotype calls and a low-coverage genome where single base
pair observations are made from sparse coverage.
'''


import argparse
import sys

import numpy
import pandas
import pysam

import freqs
import ibd_hmm
import results


def read_plink_map(gmap_fn, chrom):
    try:
        gmap_df = (
            pandas.read_csv(
                gmap_fn,
                sep=' ',
                names=["chromosome", "id", "genetic_position", "physical_position"],
            )
            .set_index("chromosome")
            .loc[chrom]
            .reset_index()
            .sort_values("physical_position")
        )
    except KeyError as e:
        raise KeyError(f"Chromosome/scaffold '{chrom}' not found in genetic map.")

    diffs = (
        gmap_df["genetic_position"]
        - numpy.roll(gmap_df["genetic_position"], 1)
    )[1:]
    if (diffs < 0).any():
        raise ValueError("Genetic positions are not monotonically increasing.")

    return gmap_df


def make_obs_from_bam(args, obs_pos):
    '''
    Make a DataFrame of observed bases from a bam file for the specific
    positions.

    Args:
        obs_pos: Positions of interest at which to make observations.

        From args namespace:
        bam_fn: Path to bam file of aligned sequences.
        chrom: Chromosome
        min_mq: Minimum mapping quality required to make a base observation.
        min_bq: Minimum base quality required to make a base observation.
        max_cov: Maximum acceptable coverage for observed site.
    Returns:
        A pandas DataFrame containing a single base observed from each site
        in obs_pos (when possible) indexed by position.
    '''
    bases = set('ACGT')
    with pysam.AlignmentFile(args.bam_fn, 'r') as bam_in:
        # pileup coords are 1-based, but these are 0-based.
        pileup_iter = bam_in.pileup(args.chrom)

        obs_pos_base = []
        pos_set = set(obs_pos)
        for col in pileup_iter:
            if ((col.reference_pos + 1) not in pos_set
                    or col.nsegments > args.max_cov):
                continue

            map_quals = col.get_mapping_qualities()
            base_quals = col.get_query_qualities()
            query_seqs = col.get_query_sequences()

            ok_bases = [
                base.upper()
                for mq, bq, base in zip(map_quals, base_quals, query_seqs)
                if mq >= args.min_mq and bq >= args.min_bq
            ]
            if not ok_bases:
                continue

            base = numpy.random.choice(ok_bases)
            if base in bases:
                obs_pos_base.append((col.reference_pos + 1, base))

    low_obs_df = pandas.DataFrame(obs_pos_base, columns=['pos', 'base'])
    low_obs_df.set_index('pos', inplace=True)
    return low_obs_df


def make_simulated_obs_from_vcf(args, vcf_in, obs_pos):
    '''
    Make a DataFrame of observed bases from a VCF file for testing.

    Args:
        vcf_in: VCF file of genotype calls
        obs_pos: Positions of interest at which to make observations.
        args: namespace containing the optional arguments
    Returns:
        A pandas DataFrame containing a single base observed from each site
        in obs_pos (when possible) indexed by position.
    '''
    def base_error(orig_base):
        '''
        Simulate a base call error by picking a base at random that is not
        the correct one.
        '''
        return numpy.random.choice([base for base in 'ACGT'
                                    if base != orig_base])

    obs_pos_base = []

    pos_cov = numpy.random.poisson(args.sim_coverage, obs_pos.shape[0])
    obs_mask = (pos_cov > 0) & (pos_cov <= args.max_cov)
    obs_chrm = numpy.random.choice([0, 1], obs_pos.shape[0])

    obs_chrm_by_pos = {obs_pos[i]: obs_chrm[i]
                       for i in range(obs_pos.shape[0]) if obs_mask[i]}

    for rec in vcf_in.fetch(contig=args.chrom):
        geno = rec.samples[args.sim_indv]['GT']

        if any(g is None for g in geno) or rec.pos not in obs_chrm_by_pos:
            continue

        base = rec.alleles[geno[obs_chrm_by_pos[rec.pos]]]
        if numpy.random.binomial(1, args.sim_error_rate) != 0:
            base = base_error(base)
        obs_pos_base.append((rec.pos, base))

    low_obs_df = pandas.DataFrame(obs_pos_base, columns=['pos', 'base'])
    low_obs_df.set_index('pos', inplace=True)
    return low_obs_df


def apply_ld_filter(args, ld_df, low_obs_df, frqs):
    """
    Filter low coverage observations by R-squared LD metric. LD statistics are
    stored in a DataFrame along with the chromosome and the two positions,
    ordered with left-most (lower) position as position 1. Pairs that do
    not appear in the DataFrame as assumed to be unlinked. For each pair
    of positions with low coverage observations that appear in the LD table,
    if the R^2 value exceeds the cutoff, exclude the position with the
    larger minor allele frequency.

    Args:
        args: namespace containing optional arguments (max_r2)
        ld_df: pandas DataFrame containing LD statistics.
        low_obs_df: pandas DataFrame containing single base observations,
                    indexed by position.
        frqs: A set of allele frequencies.
    Returns:
        The low coverage DataFrame after LD pruning.
    """
    print('Applying LD filter')
    print('...filtering to only observed sites')
    ld_low_df = ld_df[ld_df['pos1'].isin(low_obs_df.index)
                      & ld_df['pos2'].isin(low_obs_df.index)
                      & (ld_df['r^2'] > args.max_r2)]

    excluded = set()

    # MAF look-up
    pos_maf = pandas.Series(low_obs_df.index,
        index=low_obs_df.index).map(lambda p: frqs.min_af(args.chrom, p))

    print('...sorting')
    sorted_ld_low_df = ld_low_df.sort_values(['pos2', 'pos1'])

    sorted_ld_low_df['pos1_maf'] = sorted_ld_low_df['pos1'].map(pos_maf)
    sorted_ld_low_df['pos2_maf'] = sorted_ld_low_df['pos2'].map(pos_maf)

    sorted_ld_low_df['to_exclude'] = numpy.where(
        sorted_ld_low_df['pos1_maf'] < sorted_ld_low_df['pos2_maf'],
        sorted_ld_low_df['pos2'],
        sorted_ld_low_df['pos1']
    )
    print('...iterating')
    for row in sorted_ld_low_df.itertuples():
        if row.pos1 not in excluded and row.pos2 not in excluded:
            excluded.add(row.to_exclude)

    print('Excluded {} SNPs due to high LD'.format(len(excluded)))

    return low_obs_df[~low_obs_df.index.isin(excluded)]


def add_genetic_positions(low_obs_df, gmap_df):
    """
        Add a column for genetic position to the low-coverage observation
        DataFrame using the supplied genetic map and linear interpolation on
        the observed physical positions. Remove sites with duplicate genetic
        positions, keeping the first appearance.

        Args:
            low_obs_df: a DataFrame containing a "physical_position" column.
            gmap_df: a DataFrame mapping "physical_position" to "genetic_position"
        Returns:
            The modified DataFrame
    """
    low_obs_df["genetic_position"] = numpy.interp(
        low_obs_df.index,
        gmap_df["physical_position"],
        gmap_df["genetic_position"],
    )

    return low_obs_df.drop_duplicates("genetic_position")


def make_genotypes_for_indv_from_vcf(args, vcf_in, indv):
    """
    Makes a DataFrame of genotypes for a single individual from a VCF file.

    Args:
        vcf_in: VCF file input for the chromosome of interest.
        indv: ID of the individual of interest.
    Returns:
        A pandas DataFrame containing genotype base tuples index by position
    """
    pos = []
    genotypes = []
    for rec in vcf_in.fetch(contig=args.chrom):
        geno = rec.samples[indv]['GT']

        if any(g is None for g in geno):
            continue

        pos.append(rec.pos)
        genotypes.append(tuple(rec.alleles[g] for g in geno))

    hi_geno_df = pandas.DataFrame({'pos': pos, 'genotype':genotypes})
    hi_geno_df.set_index('pos', inplace=True)
    return hi_geno_df


def encode_hmm_input(args, low_obs_df, hi_geno_df, frqs):
    """
    Makes the input for the IBD HMM.

    Args:
        args: namespace containing the optional arguments
        low_obs_df: DataFrame of low coverage base observations from
                    historical individual indexed by position.
        hi_geno_df: DataFrame of genotypes from high coverage, modern
                    individual indexed by position.
        frqs: A set of allele frequencies.
    Returns:
        hmm_observed: Number of matches with the historical base found in the
                      modern individual (0, 1, 2) for each position
                      (numpy array)
        hmm_trs_probs: Tuple of two numpy arrays containing the transition
                       probabilities of remaining in the ibd and no-ibd states.
        hmm_low_freqs: The frequency in the reference population of the base
                       observed in the low coverage, historical individual.
    """
    genotype_bases = hi_geno_df.loc[low_obs_df.index, 'genotype'].apply(pandas.Series)

    hmm_observed = genotype_bases.eq(low_obs_df['base'], axis=0).sum(axis=1).values

    hmm_low_freqs = numpy.array([frqs.frequency(args.chrom, p, row['base'])
                                 for p, row in low_obs_df.iterrows()])

    hmm_trs_probs = ibd_hmm.get_state_transitions(
        low_obs_df.index,
        low_obs_df["genetic_position"],
        gens=args.ngen,
    )
    return hmm_observed, hmm_trs_probs, hmm_low_freqs


def run_ibd_hmm(args, hmm_inputs):
    """
    Run the IBD HMM with the given input.

    Args:
        args: namespace containing the optional arguments
        hmm_inputs: a tuple containing...
            hmm_observed: Number of matches with the historical base found in
                          the modern individual (0, 1, 2) for each position
                          (numpy array)
            hmm_trs_probs: Tuple of two numpy arrays containing the transition
                           probabilities of remaining in the ibd and no-ibd
                           states.
            hmm_low_freqs: The frequency in the reference population of the
                           base observed in the low coverage, historical
                           individual.
    Returns:
        hmm_post_probs: array containing the posterior probability of being
                        in an IBD segment for each position.
    """
    hmm_observed, hmm_trs_probs, hmm_low_freqs = hmm_inputs
    ibd_trs, noibd_trs = hmm_trs_probs

    assert (ibd_trs > 0.0).all()
    assert (ibd_trs < 1.0).all()
    assert (noibd_trs > 0.0).all()
    assert (noibd_trs < 1.0).all()

    hmm_post_probs = ibd_hmm.forward_backward(gens=args.ngen,
                                              observations=hmm_observed,
                                              freqs=hmm_low_freqs,
                                              ibd_trs=ibd_trs,
                                              noibd_trs=noibd_trs)
    return hmm_post_probs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("chrom", metavar="CHROM", type=str, default="1",
                        help="Chromosome ID")
    parser.add_argument("bam_fn", metavar="file.bam", type=str,
                        help="BAM file containing aligned reads from "
                             "historical individual.")
    parser.add_argument("vcf_fn", metavar="file.vcf", type=str,
                        help="VCF file containing modern individual(s).")
    parser.add_argument("frq_fn", metavar="frqs.count", type=str,
                        help="Allele counts by SNP site")
    parser.add_argument("gmap_fn", metavar="genetic_map.map", type=str,
                        help="Genetic map in Plink format.")
    parser.add_argument("-i", "--indv", metavar="ID",
                        help="Individual in VCF to test.")
    parser.add_argument("-q", "--map-quality", dest='min_mq', metavar="N",
                        type=int, default=30, help="Minimum mapping quality.")
    parser.add_argument("-Q", "--base-quality", dest='min_bq', metavar="N",
                        type=int, default=30, help="Minimum base quality.")
    parser.add_argument("-c", "--max-coverage", dest='max_cov', metavar="N",
                        type=int, default=1,
                        help="Exclude sites covered by more than N fragments.")
    parser.add_argument("--ld-r2", dest="ld_fn", metavar="ld.tab",
                        help="Tab file of LD R^2 statistics",
                        type=str, default=None)
    parser.add_argument("-r", "--max-r2", help="Maximum R^2 for LD filter",
                        dest="max_r2", type=float, default=0.0)
    parser.add_argument("-g", "--gen", metavar="N", dest="ngen",
                        type=int, default=5,
                        help="Approximate number of generations between "
                             "low-coverage and high-coverage individuals.")
    parser.add_argument("-m", "--min-run", dest="min_run",
                        type=float, default=0.8,
                        help="Minimum post. prob to allow in a detected "
                             "IBD segment.")
    parser.add_argument("-M", "--max-run", dest="max_run", type=float,
                        metavar="M", default=0.98,
                        help="Call IBD runs using post. probs exceeding M.")
    parser.add_argument("-L", "--min-len", dest="min_len", type=float,
                        metavar="cM", default=0.0,
                        help="Minimum length of IBD segment to call.")
    parser.add_argument("--merge-len", dest="merge_len", type=float,
                        metavar="cM", default=0.0,
                        help="Merge IBD segments within this distance.")
    parser.add_argument("-o", "--out-prefix", type=str, default='output',
                        help="Set prefix for the output files.")
    parser.add_argument("--sim-indv", type=str, default=None,
                        help="Simulate low-coverage using this individual "
                             "(ignores bam input).")
    parser.add_argument("--sim-vcf", dest="sim_vcf_fn", metavar="file.vcf",
                        type=str, default=None,
                        help="Use VCF for simulated low-coverage individual")
    parser.add_argument("--sim-coverage", type=float, default=None,
                        help="Fold-coverage to simulate.")
    parser.add_argument("--sim-error-rate", type=float, default=None,
                        help="Sequencing error rate for simulations.")
    parser.add_argument("--seed", type=int, default=None,
                        help="Set seed for random number generation.")
    args = parser.parse_args()

    if args.seed is not None:
        numpy.random.seed(args.seed)

    print('Reading allele frequencies...')
    frqs = freqs.AlleleFreqs()
    with open(args.frq_fn, 'r') as frq_in:
        frqs.read_vcf_counts(frq_in)

    print('Reading genetic map...')
    gmap_df = read_plink_map(args.gmap_fn, args.chrom)

    print('Reading genotypes...')
    with pysam.VariantFile(args.vcf_fn) as vcf_in:
        hi_geno_df = make_genotypes_for_indv_from_vcf(args, vcf_in, args.indv)

    if args.sim_indv:
        print('Simulating low-coverage observations...')
        sim_vcf_fn = args.sim_vcf_fn if args.sim_vcf_fn else args.vcf_fn
        with pysam.VariantFile(sim_vcf_fn) as sim_vcf_in:
            low_obs_df = make_simulated_obs_from_vcf(args,
                                                     sim_vcf_in,
                                                     hi_geno_df.index)
    else:
        print('Reading low-coverage observations...')
        low_obs_df = make_obs_from_bam(args, hi_geno_df.index)

    # We may observe bases in the low-coverage sample that are not found in
    # the reference panel. Ignore those sites (tri-allelic, likely error).
    print('Filtering to biallelic sites only...')
    biallelic_sites = numpy.array([frqs.isin(args.chrom, p, row['base'])
                                   for p, row in low_obs_df.iterrows()])
    low_obs_df = low_obs_df[biallelic_sites]

    if args.ld_fn:
        print('Reading LD r^2 statistics...')
        ld_df = pandas.read_csv(args.ld_fn, sep='\t', header=1,
                                names=['chrom', 'pos1', 'pos2', 'r^2'],
                                dtype={'chrom': str, 'pos1': int, 'pos2': int})
        low_obs_df = apply_ld_filter(args=args,
                                     ld_df=ld_df,
                                     low_obs_df=low_obs_df,
                                     frqs=frqs)

    low_obs_df = add_genetic_positions(low_obs_df, gmap_df)

    print('Observed {}/{} SNPs'.format(low_obs_df.shape[0], hi_geno_df.shape[0]))

    hmm_inputs = encode_hmm_input(args=args,
                                  low_obs_df=low_obs_df,
                                  hi_geno_df=hi_geno_df,
                                  frqs=frqs)

    hmm_post_probs = run_ibd_hmm(args, hmm_inputs)

    pos_results_df, seg_results_df = results.make_results_output(
        args=args,
        ppos=low_obs_df.index,
        gpos=low_obs_df["genetic_position"],
        hmm_post_probs=hmm_post_probs)
    pos_results_df.to_csv('{}.pos.tsv'.format(args.out_prefix),
                          index=False, sep='\t', float_format='%.6f')
    seg_results_df.to_csv('{}.seg.tsv'.format(args.out_prefix),
                          index=False, sep='\t')
    return 0


if __name__ == '__main__':
    sys.exit(main())
