#! /usr/bin/env python
'''
tjbd detects IBD segments shared between a genome sequenced to high-coverage
with complete genotype calls and a low-coverage genome where single base
pair obserations are made from sparse coverage.
'''

import argparse
import numpy
import sys


def make_obs_from_pileup(pileup_in):
    '''
    Make an array of observed bases from pileup format input.
    '''
    # TODO: this
    pass


def make_genotypes_from_vcf(vcf_in, include_indvs, exclude_indvs):
    """
    Makes a matrix of genotypes from a VCF file.

    Args:
        vcf_in: VCF file input for the chromosome of interest.
        include_indvs: list of individuals to include.
        exclude_indvs: list of individuals to exclude.
    Returns:
        positions: A vector of chromosome positions where an observation
                   was made.
        genotypes: matrix of genotypes, one column per individual,
                   one row per site.
    """
    # TODO: consider storing genotypes as low-coverage sample match counts.
    pos = list()
    genotypes = list()
    # TODO: get all individuals filter for includes, remove excludes.
    for rec in vcf_in:
        pos.append(rec.pos)
        pos_genotypes = []
        for indv in indvs:
            _ = rec.alts # this avoids a segfault
            geno = rec.samples[indv]['GT']
            pos_genotypes.append(geno)
            # TODO: may need to deal with empty observations here some how.
        genotypes.append(tuple(pos_genotypes))
    # TODO: see if we can name the columns per individual
    return numpy.array(obs_pos), numpy.array(genotypes)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("vcf_fn", metavar="file.vcf", type=str,
                        help="VCF file containing modern individual(s).")
    parser.add_argument("pu_fn", metavar="file.pileup", type=str,
                        help="Pileup file of low-coverage base observations.")
    parser.add_argument("frq_fn", metavar="frqs.count", type=str,
                        help="Allele counts by SNP site")
    parser.add_argument("rec_fn", metavar="recmap.tab", type=str,
                        help="Genetic distances in tab file.")
    parser.add_argument("-c", "--chrom", metavar="CHROM", type=str, default=1,
                        help="Chromosome ID")
    parser.add_argument("-q", "--base-quality", metavar="N", type=int,
                        default=30, help="Minimum base quality.")
    parser.add_argument("-g", "--gen", metavar="N", dest="ngen",
                        type=int, default=5,
                        help="Approximate number of generations between "
                             "low-coverage and high-coverage individuals.")
    parser.add_argument("-m", "--min-run", dest="min_run",
                        type=float, default=0.8,
                        help="Minimum post. prob to allow in a detected "
                             "IBD segment.")
    parser.add_argument("-M", "--max-run", dest="max_run", type=float,
                        metavar="M", default=0.98,
                        help="Call IBD runs using post. probs exceeding M.")
    parser.add_argument("-L", "--min-len", dest="min_len", type=float,
                        metavar="cM", default=0.0,
                        help="Minimum length of IBD segment to call.")
    parser.add_argument("-o", "--out-dir", type=str, default='trial',
                        help="Set the name of the output directory.")
    args = parser.parse_args()

    frqs = freqs.AlleleFreqs()
    with open(args.frq_fn, 'r') as frq_in:
        frqs.read_vcf_counts(frq_in)

    rmap = recmap.RecMap()
    with open(args.rec_fn, 'r') as rec_in:
        rmap.read_tab(rec_in)

    return 0


if __name__ == '__main__':
    sys.exit(main())
