#! /usr/bin/env python
'''
tjbd detects IBD segments shared between a genome sequenced to high-coverage
with complete genotype calls and a low-coverage genome where single base
pair obserations are made from sparse coverage.
'''

from __future__ import print_function, division
import sys
import argparse

import numpy
import pandas
import pysam

import freqs
import recmap
import ibd_hmm


def make_obs_from_pileup(bamfile_in, obs_pos, args):
    '''
    Make a DataFrame of observed bases from pileup format input.

    Args:
        bamfile_in: Sequences aligned to a reference sequence.
        chrom: Chromosome of interest.
        obs_pos: Positions of interest at which to make observations.
        min_mq: Minimum mapping quality required to make a base observation.
        min_mq: Minimum base quality required to make a base observation.
    Returns:
        A pandas DataFrame containing a single base observed from each site
        in obs_pos (when possible) indexed by position.
    '''
    # pileup coords are 1-based, but these are 0-based.
    pileup_iter = bamfile_in.pileup(args.chrom)

    obs_pos_base = []
    pos_set = set(obs_pos)
    for col in pileup_iter:
        if col.reference_pos not in pos_set or col.nsegments != 1:
            continue

        map_quals = col.get_mapping_qualities()
        if not map_quals or map_quals[0] < args.min_mq:
            continue
        base_quals = col.get_query_qualities()
        if not base_quals or base_quals[0] < args.min_bq:
            continue

        base = col.get_query_sequences()[0].upper()
        if base in 'ACGT':
            obs_pos_base.append((col.reference_pos, base))

    low_obs_df = pandas.DataFrame(obs_pos_base, columns=['pos', 'base'])
    low_obs_df.set_index('pos', inplace=True)
    return low_obs_df


def make_genotypes_for_indv_from_vcf(vcf_in, indv):
    """
    Makes a DataFrame of genotypes for a single individual from a VCF file.

    Args:
        vcf_in: VCF file input for the chromosome of interest.
        indv: ID of the individual of interest.
    Returns:
        A pandas DataFrame containing genotype base tuples index by position
    """
    pos = []
    genotypes = []
    for rec in vcf_in:
        geno = rec.samples[indv]['GT']

        if any(g is None for g in geno):
            continue

        pos.append(rec.pos)
        genotypes.append(tuple(rec.alleles[g] for g in geno))

    hi_geno_df = pandas.DataFrame({'pos': pos, 'genotype':genotypes})
    hi_geno_df.set_index('pos', inplace=True)
    return hi_geno_df


def encode_hmm_input(args, low_obs_df, hi_geno_df, rec_map, frqs):
    """
    Makes the input for the IBD HMM.

    Args:
        args: namespace containing the optional arguments
        low_obs_df: DataFrame of low coverage base observations from
                    historical individual indexed by position.
        hi_geno_df: DataFrame of genotypes from high coverage, modern
                    individual indexed by position.
        rec_map: A recombination map.
        frqs: A set of allele frequencies.
    Returns:
        hmm_observed: Number of matches with the historical base found in the
                      modern individual (0, 1, 2) for each position
                      (numpy array)
        hmm_trs_probs: Tuple of two numpy arrays containing the transition
                       probabilities of remaining in the ibd and no-ibd states.
        hmm_low_freqs: The frequency in the reference population of the base
                       observed in the low coverage, historical individual.
    """
    genotype_bases = hi_geno_df.loc[low_obs_df.index, 'genotype'].apply(pandas.Series)
    hmm_observed = genotype_bases.eq(low_obs_df['base'], axis=0).sum(axis=1).values

    hmm_low_freqs = numpy.array([frqs.frequency(args.chrom, p, row['base'])
                                 for p, row in low_obs_df.iterrows()])

    hmm_trs_probs = ibd_hmm.state_trans(rec=rec_map,
                                        gens=args.ngen,
                                        chrm=args.chrom,
                                        positions=low_obs_df.index)
    return hmm_observed, hmm_trs_probs, hmm_low_freqs


def run_ibd_hmm(args, hmm_inputs):
    """
    Run the IBD HMM with the given input.

    Args:
        args: namespace containing the optional arguments
        hmm_inputs: a tuple containing...
            hmm_observed: Number of matches with the historical base found in
                          the modern individual (0, 1, 2) for each position
                          (numpy array)
            hmm_trs_probs: Tuple of two numpy arrays containing the transition
                           probabilities of remaining in the ibd and no-ibd
                           states.
            hmm_low_freqs: The frequency in the reference population of the
                           base observed in the low coverage, historical
                           individual.
    Returns:
        hmm_post_probs: array containing the posterior probability of being
                        in an IBD segment for each position.
        called_ibd: array of booleans indicated whether each marker occurs
                    within a called IBD segment given the criteria in args.
    """
    hmm_observed, hmm_trs_probs, hmm_low_freqs = hmm_inputs
    ibd_trs, noibd_trs = hmm_trs_probs

    hmm_post_probs = ibd_hmm.forward_backward(gens=args.ngen,
                                              observations=hmm_observed,
                                              freqs=hmm_low_freqs,
                                              ibd_trs=ibd_trs,
                                              noibd_trs=noibd_trs)

    called_ibd = ibd_hmm.find_ibd_blocks(post_probs=hmm_post_probs,
                                         hi_score=args.max_run,
                                         lo_score=args.min_run,
                                         pos=None,
                                         min_len=args.min_len)
    return hmm_post_probs, called_ibd


def make_results_output(args, rec_map, low_obs_df, hmm_post_probs, called_ibd):
    """
    Returns:
        pos_results_df: a DataFrame containing the positional results from
                        the HMM scan.
        seg_results_df: a DataFrame containing the results summarized by
                        segment.
    """
    gpos = low_obs_df.index.map(lambda x: rec_map.position(args.chrom, x))
    pos_results_df = pandas.DataFrame({'chrom': args.chrom,
                                       'pos':low_obs_df.index,
                                       'gpos':gpos,
                                       'posterior':hmm_post_probs,
                                       'ibd_call':called_ibd})
    # TODO: add results by segment.
    return pos_results_df[['chrom', 'pos', 'gpos', 'posterior', 'ibd_call']]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("chrom", metavar="CHROM", type=str, default="1",
                        help="Chromosome ID")
    parser.add_argument("bam_fn", metavar="file.bam", type=str,
                        help="BAM file containing aligned reads from "
                             "historical individual.")
    parser.add_argument("vcf_fn", metavar="file.vcf", type=str,
                        help="VCF file containing modern individual(s).")
    parser.add_argument("frq_fn", metavar="frqs.count", type=str,
                        help="Allele counts by SNP site")
    parser.add_argument("rec_fn", metavar="recmap.tab", type=str,
                        help="Genetic distances in tab file.")
    parser.add_argument("-i", "--indv", metavar="ID",
                        help="Individual in VCF to test.")
    parser.add_argument("-q", "--map-quality", dest='min_mq', metavar="N",
                        type=int, default=30, help="Minimum mapping quality.")
    parser.add_argument("-Q", "--base-quality", dest='min_bq', metavar="N",
                        type=int, default=30, help="Minimum base quality.")
    parser.add_argument("-g", "--gen", metavar="N", dest="ngen",
                        type=int, default=5,
                        help="Approximate number of generations between "
                             "low-coverage and high-coverage individuals.")
    parser.add_argument("-m", "--min-run", dest="min_run",
                        type=float, default=0.8,
                        help="Minimum post. prob to allow in a detected "
                             "IBD segment.")
    parser.add_argument("-M", "--max-run", dest="max_run", type=float,
                        metavar="M", default=0.98,
                        help="Call IBD runs using post. probs exceeding M.")
    parser.add_argument("-L", "--min-len", dest="min_len", type=float,
                        metavar="cM", default=0.0,
                        help="Minimum length of IBD segment to call.")
    parser.add_argument("-o", "--out-dir", type=str, default='trial',
                        help="Set the name of the output directory.")
    args = parser.parse_args()

    frqs = freqs.AlleleFreqs()
    with open(args.frq_fn, 'r') as frq_in:
        frqs.read_vcf_counts(frq_in)

    rec_map = recmap.RecMap()
    with open(args.rec_fn, 'r') as rec_in:
        rec_map.read_tab(rec_in)

    with pysam.VariantFile(args.vcf_fn) as vcf_in:
        hi_geno_df = make_genotypes_for_indv_from_vcf(vcf_in, args.indv)

    with pysam.AlignmentFile(args.bam_fn, 'r') as bam_in:
        low_obs_df = make_obs_from_pileup(bam_in, hi_geno_df.index, args)

    print('Observed {}/{} SNPs'.format(low_obs_df.shape[0], hi_geno_df.shape[0]))

    hmm_inputs = encode_hmm_input(args=args,
                                  low_obs_df=low_obs_df,
                                  hi_geno_df=hi_geno_df,
                                  rec_map=rec_map,
                                  frqs=frqs)

    hmm_post_probs, called_ibd = run_ibd_hmm(args, hmm_inputs)

    pos_results_df = make_results_output(args=args,
                                         rec_map=rec_map,
                                         low_obs_df=low_obs_df,
                                         hmm_post_probs=hmm_post_probs,
                                         called_ibd=called_ibd)
    pos_results_df.to_csv('output.tsv', index=False, sep='\t')
    print(pos_results_df)
    return 0


if __name__ == '__main__':
    sys.exit(main())
